cc_library(
  name = "ecs",
  hdrs = [
    "include/ecs/Entity.h",
    "include/ecs/Manager.h",
    "include/ecs/ComponentStorage.h",
  ],
  srcs = [
    "src/Entity.cc",
    "src/Manager.cc",
  ],
  includes = [
    "include"
  ],
  visibility = ["//visibility:public"],
)
